# Generated by Django 5.0.2 on 2024-03-25 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='descMovimenti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrizione', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Incasso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('descrizione', models.CharField(blank=True, max_length=100, null=True)),
                ('totaleCassa', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('incassoPresunto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('differenza', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='images')),
                ('incasso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='incassi.incasso')),
            ],
        ),
        migrations.CreateModel(
            name='Dettagli',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrata', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('uscita', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('movimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incassi.descmovimenti')),
                ('incasso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incassi.incasso')),
            ],
        ),
    ]
